### ISSUE TITLE
"Back to top" link at category headings to quickly get to "Table of Contents"

### ISSUE THREAD

**Issue by wohfab** [marekbrze/categorized-raycast-extensions#2]
I would suggest, adding a **"Back to top" link at the headings of each category.** This makes browsing the list and quickly getting back to the "Table of Contents" easier and more fun.

The [awesome selfhosted repo](https://github.com/awesome-selfhosted/awesome-selfhosted/blob/master/README.md#software) is a good example for an easy implementation of this. They use something like this:

```
**[`^        back to top        ^`](#table-of-contents)**
```

Which looks like this:

**[`^        back to top        ^`](#table-of-contents)**

Adding this below the category headings would be an awesome addition to this very useful repo!

**Comment by marekbrze** [comment]
Hi @wohfab!

Thanks for the suggestion! Just added it to the script generating markdown! Enjoy!

**Comment by marekbrze** [comment]
Done in https://github.com/marekbrze/categorized-raycast-extensions/commit/be11bbd1b5122cbaebe4869562f5daafd67cf6f5
