### ISSUE TITLE
How often is the list getting updated?

### ISSUE THREAD

**Issue by BossElijah** [marekbrze/categorized-raycast-extensions#4]
Hey there @marekbrze!

I really appreciate this list, but a quick question is how often you will update it cuz it seems to not have been updated for a few months.

**Comment by dominicpratt** [comment]
That would interest me too.

**Comment by marekbrze** [comment]
Hi all,

Sorry for being silent. I will update my scripts this week and I will keep with the weekly updates then 👌 Got caught up with different projects.

**Comment by BossElijah** [comment]
> Hi all,
> 
> Sorry for being silent. I will update my scripts this week and I will keep with the weekly updates then 👌 Got caught up with different projects.

Thanks man! Maybe you could set up some automated stuff... idk, whatever you have time to do 😄

**Comment by marekbrze** [comment]
Hi, 

Finally got to update my scripts and now You can expect regular, almost-weekly updates

**Comment by dominicpratt** [comment]
... unfortunately the script does not seem to be running again for 2 months?
